# Generated by Django 3.0.7 on 2021-07-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('precondition', models.CharField(max_length=255)),
                ('postcondition', models.CharField(max_length=255)),
                ('isReadOnly', models.BooleanField(default=False)),
                ('isSingleExecution', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('xpos', models.IntegerField(blank=True, null=True)),
                ('ypos', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitynode_activity', to='model.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Application')),
                ('type', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(to='model.Category')),
            ],
            bases=('model.application',),
        ),
        migrations.CreateModel(
            name='ControlNode',
            fields=[
                ('activitynode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.ActivityNode')),
            ],
            bases=('model.activitynode',),
        ),
        migrations.CreateModel(
            name='ExecutableNode',
            fields=[
                ('activitynode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.ActivityNode')),
            ],
            bases=('model.activitynode',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Application')),
                ('type', models.CharField(max_length=255)),
                ('classes', models.CharField(max_length=255)),
                ('sorting', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('linked_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_page', to='model.Page')),
            ],
            bases=('model.application',),
        ),
        migrations.CreateModel(
            name='ActivityEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityedge_activity', to='model.Activity')),
                ('incoming_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_node', to='model.ActivityNode')),
                ('outgoing_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_node', to='model.ActivityNode')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='categories',
            field=models.ManyToManyField(to='model.Category'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('executablenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.ExecutableNode')),
                ('localPrecondition', models.CharField(max_length=255)),
                ('localPostcondition', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
            ],
            bases=('model.executablenode',),
        ),
        migrations.CreateModel(
            name='DecisionNode',
            fields=[
                ('controlnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.ControlNode')),
                ('decisionInput', models.CharField(max_length=255)),
                ('decisionInputFlow', models.CharField(max_length=255)),
            ],
            bases=('model.controlnode',),
        ),
        migrations.CreateModel(
            name='FinalNode',
            fields=[
                ('controlnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.ControlNode')),
            ],
            bases=('model.controlnode',),
        ),
        migrations.CreateModel(
            name='ForkNode',
            fields=[
                ('controlnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.ControlNode')),
            ],
            bases=('model.controlnode',),
        ),
        migrations.CreateModel(
            name='InitialNode',
            fields=[
                ('controlnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.ControlNode')),
            ],
            bases=('model.controlnode',),
        ),
        migrations.CreateModel(
            name='JoinNode',
            fields=[
                ('controlnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.ControlNode')),
                ('joinSpec', models.CharField(max_length=255)),
                ('isCombineDuplicate', models.BooleanField(default=True)),
            ],
            bases=('model.controlnode',),
        ),
        migrations.CreateModel(
            name='MergeNode',
            fields=[
                ('controlnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.ControlNode')),
            ],
            bases=('model.controlnode',),
        ),
        migrations.CreateModel(
            name='ActivityFinalNode',
            fields=[
                ('finalnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.FinalNode')),
            ],
            bases=('model.finalnode',),
        ),
        migrations.CreateModel(
            name='FlowFinalNode',
            fields=[
                ('finalnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.FinalNode')),
            ],
            bases=('model.finalnode',),
        ),
        migrations.CreateModel(
            name='OperationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('String', 'string'), ('Int', 'int'), ('Bool', 'bool')], default=None, max_length=20)),
                ('implementation', models.TextField(default='raise NotImplementedError')),
                ('callOperationAction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='model.Action')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='callBehaviorAction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callBehaviorAction', to='model.Action'),
        ),
    ]
