version: '3.1'

services:
  corenlp:
    build:
      context: "."
      dockerfile: "Dockerfile.corenlp"
  django:
    build:
      context: "."
      dockerfile: "Dockerfile.django"
    restart: always
    command: >
      sh -c "
        python manage.py migrate --noinput && 
        gunicorn --bind :8000 --workers 5 --threads 10 --timeout 600 --log-level debug backend.wsgi:application
      "
    volumes:
      - ./src:/code
      - ./conf/settings.py:/code/backend/settings.py
    depends_on:
      - corenlp
  nginx:
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - django
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./pub:/usr/share/nginx/html