# Generated by Django 3.0.7 on 2020-08-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
