# Generated by Django 3.0.7 on 2020-08-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_grade_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
