# Generated by Django 3.0.7 on 2020-08-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
