# Generated by Django 3.0.7 on 2020-09-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0027_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
