# Generated by Django 3.0.7 on 2020-09-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0033_delete_multipleproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
