# Generated by Django 3.0.7 on 2020-09-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0039_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
