# Generated by Django 3.0.7 on 2020-09-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0050_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleProduct',
        ),
    ]
