# Generated by Django 3.0.7 on 2020-10-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0060_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
