# Generated by Django 3.0.7 on 2020-10-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0086_delete_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
