# Generated by Django 3.0.7 on 2020-10-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0091_grade_multipleproduct_order_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
