# Generated by Django 3.0.7 on 2020-10-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0092_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleProduct',
        ),
    ]
