# Generated by Django 3.0.7 on 2020-10-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0097_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
