# Generated by Django 3.0.7 on 2020-10-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0122_delete_multipleproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
