# Generated by Django 3.0.7 on 2020-10-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0124_customer_multipleproduct_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
