# Generated by Django 3.0.7 on 2020-10-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0125_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
