# Generated by Django 3.0.7 on 2020-10-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0128_customer_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
