# Generated by Django 3.0.7 on 2020-10-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0135_customer_order_severalproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
