# Generated by Django 3.0.7 on 2020-10-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0139_customer_grade_multipleproduct_order_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
