# Generated by Django 3.0.7 on 2020-10-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0142_delete_multipleproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
