# Generated by Django 3.0.7 on 2020-10-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0145_customer_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
