# Generated by Django 3.0.7 on 2020-10-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0154_grade_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
