# Generated by Django 3.0.7 on 2020-10-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0156_auto_20201012_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
