# Generated by Django 3.0.7 on 2020-10-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0160_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
