# Generated by Django 3.0.7 on 2020-10-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0174_auto_20201021_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
