# Generated by Django 3.0.7 on 2020-10-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0182_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
