# Generated by Django 3.0.7 on 2020-10-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0225_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
