# Generated by Django 3.0.7 on 2020-10-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0227_auto_20201021_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
