# Generated by Django 3.0.7 on 2020-10-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0237_delete_citizen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
