# Generated by Django 3.0.7 on 2020-10-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0257_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
