# Generated by Django 3.0.7 on 2020-10-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0264_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
