# Generated by Django 3.0.7 on 2020-10-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0267_citizen_complaint_grade_order_product_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
