# Generated by Django 3.0.7 on 2020-10-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0269_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
