# Generated by Django 3.0.7 on 2020-10-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0273_delete_citizen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
