# Generated by Django 3.0.7 on 2020-11-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0275_citizen_complaint_customer_grade_order_product_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourLeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
