# Generated by Django 3.0.7 on 2020-11-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0277_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
