# Generated by Django 3.0.7 on 2020-11-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0278_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
