# Generated by Django 3.0.7 on 2020-11-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0281_auto_20201112_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
