# Generated by Django 3.0.7 on 2020-11-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0282_delete_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
