# Generated by Django 3.0.7 on 2020-11-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0289_auto_20201123_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
