# Generated by Django 3.0.7 on 2020-11-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0302_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
