# Generated by Django 3.0.7 on 2021-01-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0311_auto_20210107_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
