version: '3.1'

services:
  corenlp:
    build:
      context: "."
      dockerfile: "Dockerfile.corenlp"
  django:
    build:
      context: "."
      dockerfile: "Dockerfile.django"
    restart: always
    command: >
      sh -c "
        pip install debugpy -t /tmp &&
        python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 
        gunicorn --bind :8000 --workers 5 --threads 10 --timeout 600 --log-level debug backend.wsgi:application
      "
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./src:/code
      - ./conf/settings.py:/code/backend/settings.py
    depends_on:
      - corenlp
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
    volumes:
      - ./cert:/cert
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./pub:/usr/share/nginx/html
