# Generated by Django 3.0.7 on 2020-08-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
