# Generated by Django 3.0.7 on 2020-08-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Teacher',
        ),
    ]
