# Generated by Django 3.0.7 on 2020-08-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_customer_grade_order_product_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
