# Generated by Django 3.0.7 on 2020-08-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0017_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
