# Generated by Django 3.0.7 on 2020-08-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0018_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
