# Generated by Django 3.0.7 on 2020-09-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0021_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
