# Generated by Django 3.0.7 on 2020-09-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0035_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
