# Generated by Django 3.0.7 on 2020-09-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0037_grade_multipleproducts_order_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
