# Generated by Django 3.0.7 on 2020-09-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0042_grade_multipleproduct_order_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
