# Generated by Django 3.0.7 on 2020-09-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0054_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
