# Generated by Django 3.0.7 on 2020-10-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0057_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleProduct',
        ),
    ]
