# Generated by Django 3.0.7 on 2020-10-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0059_grade_multipleproduct_order_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
