# Generated by Django 3.0.7 on 2020-10-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0066_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
