# Generated by Django 3.0.7 on 2020-10-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0067_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleProduct',
        ),
    ]
