# Generated by Django 3.0.7 on 2020-10-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0071_auto_20201003_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleProduct',
        ),
    ]
