# Generated by Django 3.0.7 on 2020-10-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0074_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
