# Generated by Django 3.0.7 on 2020-10-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0075_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleProduct',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
