# Generated by Django 3.0.7 on 2020-10-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0082_grade_multipleproduct_order_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='MultipleProduct',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
