# Generated by Django 3.0.7 on 2020-10-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0084_customer_multipleproduct_order_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
