# Generated by Django 3.0.7 on 2020-10-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0093_delete_multipleproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
