# Generated by Django 3.0.7 on 2020-10-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0113_auto_20201007_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleProduct',
        ),
    ]
