# Generated by Django 3.0.7 on 2020-10-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0118_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
