# Generated by Django 3.0.7 on 2020-10-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0133_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeveralProduct',
        ),
    ]
