# Generated by Django 3.0.7 on 2020-10-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0137_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeveralProduct',
        ),
    ]
