# Generated by Django 3.0.7 on 2020-10-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0140_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
