# Generated by Django 3.0.7 on 2020-10-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0155_auto_20201012_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
