# Generated by Django 3.0.7 on 2020-10-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0161_auto_20201021_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
