# Generated by Django 3.0.7 on 2020-10-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0191_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
    ]
