# Generated by Django 3.0.7 on 2020-10-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0192_delete_citizen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
