# Generated by Django 3.0.7 on 2020-10-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0198_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
