# Generated by Django 3.0.7 on 2020-10-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0206_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
