# Generated by Django 3.0.7 on 2020-10-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0212_auto_20201021_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
