# Generated by Django 3.0.7 on 2020-10-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0233_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
