# Generated by Django 3.0.7 on 2020-10-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0268_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
