# Generated by Django 3.0.7 on 2020-11-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0280_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
