# Generated by Django 3.0.7 on 2020-11-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0285_aisle_supermarket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supermarket',
        ),
    ]
