# Generated by Django 3.0.7 on 2020-11-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0290_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
