# Generated by Django 3.0.7 on 2020-11-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0294_businesscourse_course_coursecoordinator_lecture_sciencecourse_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
