# Generated by Django 3.0.7 on 2020-11-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0295_auto_20201124_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
