# Generated by Django 3.0.7 on 2020-11-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0299_delete_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessCourse',
        ),
        migrations.DeleteModel(
            name='ScienceCourse',
        ),
    ]
