# Generated by Django 3.0.7 on 2020-11-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0300_auto_20201125_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCoordinator',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
