# Generated by Django 3.0.7 on 2020-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0304_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
