# Generated by Django 3.0.7 on 2021-01-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0310_delete_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessCourse',
        ),
        migrations.DeleteModel(
            name='ScienceCourse',
        ),
    ]
