# Generated by Django 3.0.7 on 2020-09-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_requirement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
