# Generated by Django 3.0.7 on 2020-11-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data/%Y-%m-%d')),
            ],
        ),
    ]
