# Generated by Django 3.0.7 on 2021-02-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_abstract', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data/%Y-%m-%d')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('String', 'string'), ('Int', 'int'), ('Bool', 'bool')], max_length=20)),
                ('implementation', models.TextField(default='raise NotImplementedError')),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_classifier', to='model.Classifier')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('classifier_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_from', to='model.Classifier')),
                ('classifier_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_to', to='model.Classifier')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('raw_text', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('relationship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Relationship')),
                ('multiplicity_to', models.CharField(max_length=255)),
                ('multiplicity_from', models.CharField(max_length=255)),
                ('end_from', models.CharField(default='', max_length=255)),
                ('end_to', models.CharField(default='', max_length=255)),
            ],
            bases=('model.relationship',),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Classifier')),
            ],
            bases=('model.classifier',),
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('relationship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Relationship')),
                ('multiplicity_to', models.CharField(max_length=255)),
                ('multiplicity_from', models.CharField(max_length=255)),
                ('end_from', models.CharField(default='', max_length=255)),
                ('end_to', models.CharField(default='', max_length=255)),
            ],
            bases=('model.relationship',),
        ),
        migrations.CreateModel(
            name='Enumerator',
            fields=[
                ('classifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Classifier')),
            ],
            bases=('model.classifier',),
        ),
        migrations.CreateModel(
            name='Generalization',
            fields=[
                ('relationship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Relationship')),
            ],
            options={
                'abstract': False,
            },
            bases=('model.relationship',),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('String', 'string'), ('Int', 'int'), ('Bool', 'bool')], max_length=20)),
                ('applications', models.ManyToManyField(to='model.Application')),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier', to='model.Classifier')),
            ],
        ),
        migrations.CreateModel(
            name='OperationParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('String', 'string'), ('Int', 'int'), ('Bool', 'bool')], max_length=20)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='model.Operation')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='classifiers',
            field=models.ManyToManyField(to='model.Classifier'),
        ),
    ]
