# Generated by Django 3.0.7 on 2020-10-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_requirement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
