# Generated by Django 3.0.7 on 2020-10-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_requirement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
