# Generated by Django 3.0.7 on 2020-11-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
