# Generated by Django 3.0.7 on 2021-01-21 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('relationship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Relationship')),
                ('multiplicity_to', models.CharField(max_length=255)),
                ('multiplicity_from', models.CharField(max_length=255)),
                ('end_from', models.CharField(default='', max_length=255)),
                ('end_to', models.CharField(default='', max_length=255)),
            ],
            bases=('model.relationship',),
        ),
    ]
